prometheus:
  prometheusSpec: # probably no spec... 
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
      
    serviceMonitorSelectorNilUsesHelmValues: false


grafana:
  enabled: true
