# Deployment:
# Pod deployment, lift cycle, desired state (replicas, pods, image deploymnents and policies)

apiVersion: apps/v1 # bath jobs
kind: Deployment
metadata:
  name: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.service.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.service.name }} 
  template: # Pod definition: image deployment 
    metadata:
      labels: 
        app: {{ .Values.service.name }} 
    spec:
      containers:
        - name: {{ .Values.container.name }} 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"         
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port}}
