# Services: 
#  Pod networking and endpoint management: port mapping, selector and match label defintions. 
# since service use the same port, thus, load balances on track


apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  # name of service
  labels:
    app: {{ .Values.service.name }} # for grouping sources, and selector for matchLabels 
spec:
  selector:
    app: {{ .Values.service.name }}  # selector for pod management 
  ports:
    - name: {{ .Values.service.portName }}  # == http # to match with monitor
      port: {{ .Values.service.port }}      
      targetPort: {{ .Values.container.port }}   # container port
  type: ClusterIP      # defined port<-> targetPort mapping type; others: NodePort (nodes on static IP) ,  Loadbalancer, ExternalName
