apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggen
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: log-generator
          image: datapull:latest  # check by: eval $(minikube docker-env) then: docker images
          ports:
            - containerPort: 8066 # it does not listen to anything for the time being 
